# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiShowAuthor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 373)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_auth_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_auth_name.setFont(font)
        self.label_auth_name.setObjectName("label_auth_name")
        self.verticalLayout_2.addWidget(self.label_auth_name)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_years_life = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_years_life.setFont(font)
        self.label_years_life.setObjectName("label_years_life")
        self.verticalLayout_2.addWidget(self.label_years_life)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_country = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_country.setFont(font)
        self.label_country.setObjectName("label_country")
        self.verticalLayout_2.addWidget(self.label_country)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_save_xml = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_xml.setMinimumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_save_xml.setFont(font)
        self.button_save_xml.setObjectName("button_save_xml")
        self.verticalLayout.addWidget(self.button_save_xml)
        self.button_save_json = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_json.setMinimumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_save_json.setFont(font)
        self.button_save_json.setObjectName("button_save_json")
        self.verticalLayout.addWidget(self.button_save_json)
        self.button_close = QtWidgets.QPushButton(self.centralwidget)
        self.button_close.setMinimumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_close.setFont(font)
        self.button_close.setObjectName("button_close")
        self.verticalLayout.addWidget(self.button_close)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Информация об авторе"))
        self.label.setText(_translate("MainWindow", "Имя автора"))
        self.label_auth_name.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "Годы жизни"))
        self.label_years_life.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "Страна"))
        self.label_country.setText(_translate("MainWindow", "3"))
        self.button_save_xml.setText(_translate("MainWindow", "Сохранить в .xml"))
        self.button_save_json.setText(_translate("MainWindow", "Сохранить в .json"))
        self.button_close.setText(_translate("MainWindow", "Закрыть окно"))
